### ISSUE TITLE
Crash when tapping on floating Instabug button

### ISSUE THREAD

**Issue by Lapinou42** [Instabug/instabug-xamarin#4]
Hello, 

I have a strange bug on Xamarin.iOS (not tested Xamarin.Droid yet). When a tap on my floating instabug button,  the app crash rapidly and I get no crash log. 

I just wrote on my app delegate :
**Instabug.StartWithToken(@"myToken", IBGInvocationEvent.FloatingButton);**

I have the keys in Infos.plist: 

- NSMicrophoneUsageDescription
- NSPhotoLibraryUsageDescription

Should I do something else ? 

Thank you, 
Lapinou.

**UPDATE:**

I got an email with this infos:

Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/01D97945-E56C-4698-A59B-ACF83548808C/MyApp.iOS.app/Instabug.bundle> (not yet loaded)' with name 'IBGPromptVC-iPhone'

**Comment by Lapinou42** [comment]
Any idea ?

**Comment by DannyRabbitteer** [comment]
I have the exact same issue.

**Comment by DannyRabbitteer** [comment]
So I found a solution to this. I copied the Instabug.bundle folder's contents from the new SDK available on the Instabug dashboard https://dashboard.instabug.com to that of the Binding application (https://github.com/Instabug/instabug-xamarin/tree/master/InstabugIOSSDK). However the application still crashes, this time with no crash report. Only the application output of: `Error (47) / SpringBoard(KeyboardArbiter): HW kbd: Failed to set (null) as keyboard focus`

**Comment by Lapinou42** [comment]
Thank you ! 

I tried and indeed, it's better, but I have this crash now when I click on the floating button:

[<IBGPromptVC 0x10643f900> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key promptHeightConstraint.

Probably an IBOutlet not linked with the view controller. So, did you update the instabug.a library as well ?

**Comment by salmatarzi** [comment]
@Lapinou42 @DannyRabbitteer I know this issue has been there for a while, there is an update, where you can download the component from the Xamarin store. Please check the updated README file in the repo on how to update to the latest version. 

I will close this issue for now, please reopen if the problem still persists.
