### ISSUE TITLE
Cannot Find InstaBug class in the package Com.Instabug.Library

### ISSUE THREAD

**Issue by gupta-shubham93** [Instabug/instabug-xamarin#5]
I am trying to integrate Instabug for Android via Xamarin Studio v5.10.3 (build 51) and I followed the steps exactly mentioned but cannot find the Instabug class to invoke the Instabug Builder.

Could you please help me out?

**Comment by salmatarzi** [comment]
@gupta-shubham93 I know this issue has been there for a while, I'm really sorry for that. There is an update, where you can download the component from the Xamarin store. Please check the updated README file in the repo on how to update to the latest version.

I will close this issue for now, please reopen if the problem still persists.
