### ISSUE TITLE
Xamarin android binding

### ISSUE THREAD

**Issue by Macjon** [Instabug/instabug-xamarin#9]
Maybe an idea to add the following nuget to the android binding file: [https://github.com/mattleibow/Xamarin.Android.Bindings.Generators](https://github.com/mattleibow/Xamarin.Android.Bindings.Generators)

This nuget will add te parameter names to all the methods.

**Comment by NadineMansour** [comment]
@Macjon Thank you so much for the suggestion. 
We will take a look at it. 
I will keep you updated.

**Comment by Macjon** [comment]
If I have some time, I will add it to your project and will create a pull request.

**Comment by NadineMansour** [comment]
@Macjon I discussed it with the team. We are definitely putting your suggestion into considerations. However, I can't promise that this will be added in the near future. 
I will close the issue for now and will make sure to update you if there is any change in plans.
